### ISSUE TITLE
Create ERD

### ISSUE THREAD

**Issue by AntoineNathalie** [PotatoesFall/Quizmaster#3]
Zie requirements voor de Quizmaster, 2.1 Ojecten

5 objecten : Gebruiker, Cursus, Quiz, Vraag, Groep

Maak ERD voor bovenstaande objecten.

**Comment by PotatoesFall** [comment]
First draf is klaar voor initiele design, toekomstige veranderingen aan de database kunnen dan wel in een sql create & insert script terecht zodat het via git gedeeld word
